#! /bin/sh

bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d a b c d e
bspc desktop -n a

# focus follow mouse
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Firefox desktop=^2
bspc rule -a Google-chrome-stable desktop=^3
bspc rule -a xfreerdp floating=off desktop=^4
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a trayer floating=on

# panel
bspc config top_padding 16
tint3 &
sxhkd &
dex -a
