alias pki="sudo yum --color=auto install"
alias pkls="rpm -ql"
alias pkp="yum --color=auto provides"
alias pks="yum --color=auto search"
alias pksh="yum --color=auto info"
alias pku="sudo yum --color=auto update"
alias pkr="sudo yum --color=auto remove"
